basis/graph/builder.py, basis/node/node.py, basis/utils/modules.py
Some of the code manipulates file paths as strings, and assumes `/` as
the file separator. This PR changes that code to use pathlib instad.
=> Fix path handling on Windows

pyproject.toml
CI takes several minutes to run, and ~95% of that time is resolving and installing dependencies. Removing unused dependencies can speed that up a bit.
=> Remove some dev-dependencies not used by CI

.flake8, .github/workflows/basis.yml
We currently reinstall all dependencies for each CI run. This PR caches the poetry venv between runs, invalidating it any time `pyproject.toml` changes. This should speed up CI builds significantly.
=> Cache poetry venv

.github/workflows/basis.yml, pyproject.toml
Additionally, we cache the poetry install itself to reduce run time
further. Venvs are now cached per-python version rather than sharing a
venv between python versions.
=> Test with Python 3.10 in CI

basis/cli/commands/create.py, basis/configuration/edit.py, basis/configuration/graph.py, tests/configuration/test_config_editor.py
- Edit remaining parts of config
- Parse the builder into a config or manifest directly in memory without needing to write back to disk. This is mostly useful for tests.
=> Add more functionality to GraphConfigEditor

basis/graph/builder.py, basis/graph/configured_node.py, tests/graph/test_builder.py, tests/graph/utils.py
- Add `resolved_parameter_values` to `ConfiguredNode`
- Add exposed parameters to the `NodeInterface` of graph nodes
- Add a new error if you try to set a parameter value on a graph that doesn't define/expose that parameter.
=> Add `resolved_parameter_values` to `ConfiguredNode`

basis/cli/commands/create.py, basis/cli/main.py, basis/cli/services/api.py, basis/cli/services/output.py, tests/cli/base.py, tests/cli/test_create.py
- print help on `basis` with no commands
- Make trailing slash optional in `API_BASE_URL` envvar
- print more info for `create node`
- add response status code for blank server errors
- add subgraph creation to `create node`
- list nested subcommands on top level help
=> Improve help output

basis/cli/commands/upload.py, basis/cli/services/api.py, basis/graph/builder.py, basis/graph/configured_node.py, basis/node/node.py, tests/cli/test_upload.py, tests/graph/test_builder.py, tests/graph/utils.py
If omitted, all ports and parameters are exposed. Components must still declare an `exposes` block.
=> Make `exposes` optional for subgraphs that aren't components

basis/cli/main.py, basis/cli/services/output.py
e.g. `basis --stacktrace list graphs`
=> Add option to print stacktraces instead of error messages

basis/configuration/graph.py, basis/node/node.py
- Change `Parameter`'s `type` argument to take type instances rather than strings. 
- Support type inference for `Parameter` usage.
- Add `template` argument to `Parameter`.
- Remove runtime node function validation, since that's done at parse time now.
=> Update Parameter implementation

basis/cli/commands/list.py, basis/cli/services/api.py, basis/cli/services/list.py, tests/cli/test_list.py
Output block data is replaced by store data - PR: https://github.com/basis-os/basis-api/pull/515
Update the endpoint URL and params (output_port_name is no longer needed since you get the store data from a store node and so you pass the store node title instead)
I'm assuming more devkit changes will be coming to work with the new store node model (maybe?), this PR is mostly just to document the endpoint change. So feel free to use/revise as needed!
=> updating outblock block data endpoint

pyproject.toml
The API server uses the devkit which uses typer/click and there's a bug with typer/click (https://github.com/tiangolo/typer/issues/377), I think fixing the version of typer here, should fix the resulting issue in the API server. 
Lmk what you think! 
black (22.1.0) depends on click (>=8.0.0) and 
basis-devkit depends on click (^7.1.1), black (>=22.1.0,<23.0.0) is incompatible with basis-devkit
So I think we need to update click version in devkit to 8.0.4 (but not 8.1.0) and that will resolve these issues
=> update click version to fix bug

basis/cli/services/graph.py, basis/cli/services/lookup.py
It was only used in that file, and moving it avoids importing typer and rich when only using the editors.
=> Move `find_graph_file` into lookup.py

basis/node/node.py, pyproject.toml
Remove `Parameter(template)` and update dependencies to remove the workaround there.
=> Remove unused parameter

basis/cli/services/graph.py, basis/cli/services/upload.py, tests/cli/test_upload.py
If you name your graph yaml with a custom name, you'll have to pass it explicitly to all commands (e.g. `basis upload custom.yml`) since we still only look for `graph.yml` as a default.
=> Allow custom names for graph.yml

basis/cli/commands/upload.py, basis/cli/services/api.py, basis/cli/services/environments.py, basis/cli/services/graph_versions.py, basis/cli/services/lookup.py, basis/cli/services/organizations.py, tests/cli/test_config.py, tests/cli/test_deploy.py, tests/cli/test_list.py, tests/cli/test_trigger.py, tests/cli/test_upload.py
- GraphVersionResponse - doesn't return manifest or graph zip, but does include manifest errors
- active_graph_version -> latest_graph_version for GraphLatestResponse
- changed "/organizations/{organization_uid}/graphs/name/{name}/", to "/organizations/{organization_uid}/graphs/slug/{slug}/",
- changed "/organizations/{organization_uid}/environments/name/{name}/", to "/organizations/{organization_uid}/environments/slug/{slug}/",
- changed "/organizations/name/{name}/", to "/organizations/slug/{slug}/",
Corresponding API PR: https://github.com/basis-os/basis-api/pull/645
=> updating for v0 endpoint cleanup

patterns/cli/services/lookup.py
If you specify an `--organization`, we were previously using the configured environment id, but since this environment id doesn't exist in any other orgs, deployment would fail.
=> Require --environment with --organization

patterns/cli/main.py, pyproject.toml, tests/cli/base.py
The latest version of typer stopped using Click's help formatting code in favor of its own implementation. It's not customizable at all, so in order to support showing subcommands in help, I had to do some pretty serious monkey patching.
=> Update typer to 0.6

patterns/cli/helpers.py, patterns/cli/services/diffs.py, tests/cli/test_diffs.py, tests/cli/test_file_ignore.py
- Handle binary files when computing diffs.
- When uploading an app that doesn't have it's own .gitignore file, we now have a default list of files to ignore.
=> Upload improvements: support binary files in diff, add default ignore list

patterns/node/node.py
Since we support `Parameter(type=Connection("foo"))`
=> Add Connection to type annotation for Parameter type

.github/workflows/test.yml, mypy.ini, patterns/cli/commands/create.py, patterns/cli/commands/delete.py, patterns/cli/commands/download.py, patterns/cli/commands/list.py, patterns/cli/commands/login.py, patterns/cli/commands/logout.py, patterns/cli/commands/trigger.py, patterns/cli/commands/update.py, patterns/cli/commands/upload.py, patterns/cli/configuration/edit.py, patterns/cli/helpers.py, patterns/cli/main.py, patterns/cli/services/auth.py, patterns/cli/services/diffs.py, patterns/cli/services/login.py, tests/cli/test_create.py, tests/configuration/test_config_editor.py
- Many small typo fixes and help improvements
- Unify the three different way to add a node into a single command `add node --type=`. The `add webhook` and `add node --component` methods are kept for backwards compatibility, but are hidden from help.
- Add a connected table when adding a webhook if the table doesn't already exist
- Omit .gitignored files from diffs
- Allow ctrl-c to kill the `login` and `logout` commands
- Update the `GraphDirectoryEditor` to the latest yaml format
=> Improve various help outputs

patterns/cli/commands/download.py, patterns/cli/commands/upload.py, patterns/cli/services/diffs.py, tests/cli/test_diffs.py
Now e.g. files that exist on the remote but not locally will show as added for `download` and deleted for `upload`.
=> Show diff reversed when downloading
